import { cpSync, existsSync, mkdirSync, readdirSync, writeFileSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';
import { APP_ROOT as REPO_ROOT, DIST_DIR } from '../../server/paths.js';
import { runComposer } from './composer.js';
import { RELEASE_LAYOUT } from './layout.js';
import { PHP_DIR } from './phpBin.js';

/* The one staging function: every PHP stage — the contract suite's, the smoke
   test's, and release/php — is assembled here, so what the tests serve is
   exactly what ships.

     php/web/*        → the root (api.php, router.php, .htaccess, .user.ini,
                        config.sample.php, access-examples/, and only the
                        .htaccess of data/ and uploads/)
     php/src          → src/
     schema, seed, assets → the same names
     dist/*           → the root (index.html, render.html, static/), when asked
     vendor/          → a shim onto php/vendor (tests) or `composer install` (release)

   Never config.php: it holds the access rule and belongs to the admin, and a
   release that carried one would overwrite theirs on upload. Never anything
   in data/ or uploads/ but their .htaccess, for the same reason. */

export interface StageOptions {
  /** Copy the Vite build (dist/*) into the root: the smoke test and the release need the app shell, the contract suite doesn't. */
  dist: boolean;
  /** 'shim' reuses php/vendor (test stages); 'install' runs `composer install --no-dev -o` in the stage (the release). */
  vendor: 'shim' | 'install';
}

const WEB_DIR = join(PHP_DIR, 'web');

/** A stage without these is not worth serving: the entry points, the error-display and deny rules, and the admin's template. */
const REQUIRED_WEB_FILES = [
  'api.php',
  'router.php',
  '.htaccess',
  '.user.ini',
  'config.sample.php',
  ...RELEASE_LAYOUT.writableDirs.map((dir) => `${dir}/.htaccess`),
];

/** Deny-all in both syntaxes: Apache 2.4 (mod_authz_core) and 2.2 (still found on old shared hosts). */
const DENY_ALL = `# Written by scripts/php/stage.ts from RELEASE_LAYOUT.deniedDirs: nothing in this folder is ever served.
<IfModule mod_authz_core.c>
  Require all denied
</IfModule>
<IfModule !mod_authz_core.c>
  Order deny,allow
  Deny from all
</IfModule>
`;

/** Paths PHP reads, written with forward slashes: PHP accepts them on Windows, and they need no escaping. */
export const toPosix = (path: string) => path.replace(/\\/g, '/');

/** A single-quoted PHP string literal. */
export const phpString = (value: string) => `'${value.replace(/[\\']/g, '\\$&')}'`;

/** The test stages' vendor/autoload.php. Composer's own loader registers itself
    with prepend, so ours is registered after requiring it (again with prepend):
    that keeps the stage's own src/ first, so a stage runs exactly the code it
    ships, while opis still loads from php/vendor. */
function vendorShim(repoAutoload: string): string {
  return String.raw`<?php

declare(strict_types=1);

// Generated by scripts/php/stage.ts for a test stage. A release gets a real composer install instead.
$loader = require ${phpString(repoAutoload)};

spl_autoload_register(static function (string $class): void {
    $prefix = 'NestFlyers\\';
    if (strncmp($class, $prefix, strlen($prefix)) !== 0) {
        return;
    }
    $file = __DIR__ . '/../src/' . str_replace('\\', '/', substr($class, strlen($prefix))) . '.php';
    if (is_file($file)) {
        require $file;
    }
}, true, true);

return $loader;
`;
}

/** Copies php/web, keeping config.php out and data/ and uploads/ down to their .htaccess. */
function shipsFromWeb(source: string): boolean {
  const rel = toPosix(relative(WEB_DIR, source));
  if (rel === '') return true;
  if (rel.toLowerCase() === 'config.php') return false;
  const [top, ...rest] = rel.split('/');
  if ((RELEASE_LAYOUT.writableDirs as readonly string[]).includes(top)) {
    return rest.length === 0 || (rest.length === 1 && rest[0] === '.htaccess');
  }
  return true;
}

/** Sources land on disjoint paths; a collision (say, dist/ gaining an api.php) fails instead of silently winning. */
const COPY = { recursive: true, force: false, errorOnExist: true } as const;

/** Assembles a PHP stage in `outDir` (missing or empty) and returns its absolute path. */
export function stagePhp(outDir: string, { dist, vendor }: StageOptions): string {
  const out = resolve(outDir);
  if (existsSync(out) && readdirSync(out).length > 0) {
    throw new Error(`stagePhp: ${out} is not empty. Stage into a fresh folder, so no stale config.php or data rides along.`);
  }
  const missing = REQUIRED_WEB_FILES.filter((file) => !existsSync(join(WEB_DIR, file)));
  if (missing.length) throw new Error(`stagePhp: php/web is incomplete, missing ${missing.join(', ')}.`);
  if (dist && !existsSync(join(DIST_DIR, 'index.html'))) {
    throw new Error('stagePhp: dist/index.html is missing. Run `vite build` first.');
  }

  mkdirSync(out, { recursive: true });
  cpSync(WEB_DIR, out, { ...COPY, filter: shipsFromWeb });
  cpSync(join(PHP_DIR, 'src'), join(out, 'src'), COPY);
  for (const dir of ['schema', 'seed', 'assets']) cpSync(join(REPO_ROOT, dir), join(out, dir), COPY);
  if (dist) cpSync(DIST_DIR, out, COPY);

  // The release ships these next to api.php, so every stage has them: the deny
  // rules that hide them are then probed against files that really exist.
  for (const file of ['composer.json', 'composer.lock']) cpSync(join(PHP_DIR, file), join(out, file), COPY);

  if (vendor === 'shim') {
    const repoAutoload = join(PHP_DIR, 'vendor', 'autoload.php');
    if (!existsSync(repoAutoload)) throw new Error('stagePhp: php/vendor/autoload.php is missing. Run composer install in php/ first.');
    mkdirSync(join(out, 'vendor'));
    writeFileSync(join(out, 'vendor', 'autoload.php'), vendorShim(toPosix(repoAutoload)), { flag: 'wx' });
  } else {
    runComposer(['install', '--no-dev', '--optimize-autoloader'], out);
  }

  // Last, so vendor/ exists. data/ keeps the .htaccess php/web ships (checked above).
  for (const dir of RELEASE_LAYOUT.deniedDirs) {
    if (!existsSync(join(out, dir))) continue;
    if ((RELEASE_LAYOUT.writableDirs as readonly string[]).includes(dir)) continue;
    writeFileSync(join(out, dir, '.htaccess'), DENY_ALL, { flag: 'wx' });
  }
  return out;
}
